# Generated by Django 2.0.2 on 2018-02-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180227_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_country',
            new_name='country',
        ),
    ]
